INSERT OR IGNORE INTO brands_table (title) VALUES ('Nike');
INSERT OR IGNORE INTO brands_table (title) VALUES ('Adidas');
INSERT OR IGNORE INTO brands_table (title) VALUES ('Puma');
INSERT OR IGNORE INTO brands_table (title) VALUES ('New Balance');
INSERT OR IGNORE INTO brands_table (title) VALUES ('Mizuno');

INSERT OR IGNORE INTO categories_table (title) VALUES ('Tenis');
INSERT OR IGNORE INTO categories_table (title) VALUES ('Blusa');
INSERT OR IGNORE INTO categories_table (title) VALUES ('Camiseta');
INSERT OR IGNORE INTO categories_table (title) VALUES ('Calça');
INSERT OR IGNORE INTO categories_table (title) VALUES ('Chapéu');
INSERT OR IGNORE INTO categories_table (title) VALUES ('Acessório');
INSERT OR IGNORE INTO categories_table (title) VALUES ('Bola');

INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Nike', 80, true, 500, 1, 7, 'https://picsum.photos/seed/bs001/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Adidas', 85, true, 500, 2, 7, 'https://picsum.photos/seed/bs002/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Adidas Infantil', 50, true, 500, 2, 7, 'https://picsum.photos/seed/bs003/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Puma', 110, true, 500, 3, 7, 'https://picsum.photos/seed/bs004/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete New Balance', 80, true, 500, 4, 7, 'https://picsum.photos/seed/bs005/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Mizuno', 60, true, 500, 5, 7, 'https://picsum.photos/seed/bs006/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Infantil', 40, true, 500, 3, 7, 'https://picsum.photos/seed/bs007/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Feminina', 80, true, 500, 3, 7, 'https://picsum.photos/seed/bs008/400/300');

UPDATE products_table SET image_url = 'https://picsum.photos/seed/bs001/400/300' WHERE name = 'Bola de Basquete Nike' AND image_url IS NULL;
UPDATE products_table SET image_url = 'https://picsum.photos/seed/bs002/400/300' WHERE name = 'Bola de Basquete Adidas' AND image_url IS NULL;
UPDATE products_table SET image_url = 'https://picsum.photos/seed/bs003/400/300' WHERE name = 'Bola de Basquete Adidas Infantil' AND image_url IS NULL;
UPDATE products_table SET image_url = 'https://picsum.photos/seed/bs004/400/300' WHERE name = 'Bola de Basquete Puma' AND image_url IS NULL;
UPDATE products_table SET image_url = 'https://picsum.photos/seed/bs005/400/300' WHERE name = 'Bola de Basquete New Balance' AND image_url IS NULL;
UPDATE products_table SET image_url = 'https://picsum.photos/seed/bs006/400/300' WHERE name = 'Bola de Basquete Mizuno' AND image_url IS NULL;
UPDATE products_table SET image_url = 'https://picsum.photos/seed/bs007/400/300' WHERE name = 'Bola de Basquete Infantil' AND image_url IS NULL;
UPDATE products_table SET image_url = 'https://picsum.photos/seed/bs008/400/300' WHERE name = 'Bola de Basquete Feminina' AND image_url IS NULL;

INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Nike Air Zoom Freak 5', 299.90, true, 200, 1, 1, 'https://picsum.photos/seed/bs009/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Adidas D.O.N. Issue 5', 279.90, true, 150, 2, 1, 'https://picsum.photos/seed/bs010/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Puma Clyde Court 2024', 249.90, true, 120, 3, 1, 'https://picsum.photos/seed/bs011/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('New Balance TWO WXY v4', 289.90, true, 100, 4, 1, 'https://picsum.photos/seed/bs012/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Nike LeBron 21', 449.90, true, 80, 1, 1, 'https://picsum.photos/seed/bs013/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Adidas Harden Vol. 8', 319.90, true, 90, 2, 1, 'https://picsum.photos/seed/bs014/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Nike KD 16', 399.90, false, 0, 1, 1, 'https://picsum.photos/seed/bs015/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Adidas Anthony Edwards 1', 269.90, true, 130, 2, 1, 'https://picsum.photos/seed/bs016/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Puma MB.03', 319.90, true, 110, 3, 1, 'https://picsum.photos/seed/bs017/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('New Balance Kawhi 3', 349.90, true, 70, 4, 1, 'https://picsum.photos/seed/bs018/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Nike Giannis Immortality 4', 229.90, true, 160, 1, 1, 'https://picsum.photos/seed/bs019/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Adidas Trae Young 3', 289.90, false, 0, 2, 1, 'https://picsum.photos/seed/bs020/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Mizuno Wave Drive Z6', 259.90, true, 100, 5, 1, 'https://picsum.photos/seed/bs021/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Nike Zoom GT Cut 3', 369.90, true, 85, 1, 1, 'https://picsum.photos/seed/bs022/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Adidas Dame 9', 299.90, true, 140, 2, 1, 'https://picsum.photos/seed/bs023/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Puma All-Pro Nitro', 279.90, true, 95, 3, 1, 'https://picsum.photos/seed/bs024/400/300');

INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Blusa de Moletom Nike Basketball', 119.90, true, 300, 1, 2, 'https://picsum.photos/seed/bs025/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Moletom Adidas Hoop', 109.90, true, 250, 2, 2, 'https://picsum.photos/seed/bs026/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Moletom Puma Basketball Training', 99.90, true, 200, 3, 2, 'https://picsum.photos/seed/bs027/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Blusa de Treino New Balance Court', 89.90, true, 180, 4, 2, 'https://picsum.photos/seed/bs028/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Blusa Nike Therma-FIT Club', 129.90, true, 220, 1, 2, 'https://picsum.photos/seed/bs029/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Blusa Adidas Adicolor Essentials', 99.90, true, 240, 2, 2, 'https://picsum.photos/seed/bs030/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Moletom Mizuno Sweatshirt', 94.90, false, 0, 5, 2, 'https://picsum.photos/seed/bs031/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Blusa Nike Sportswear Club Fleece', 89.90, true, 300, 1, 2, 'https://picsum.photos/seed/bs032/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Blusa Adidas Bold Block', 104.90, true, 190, 2, 2, 'https://picsum.photos/seed/bs033/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Moletom Puma Franchise', 109.90, true, 160, 3, 2, 'https://picsum.photos/seed/bs034/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Blusa New Balance Essentials', 84.90, true, 210, 4, 2, 'https://picsum.photos/seed/bs035/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Blusa Mizuno Heritage', 94.90, true, 170, 5, 2, 'https://picsum.photos/seed/bs036/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Blusa Nike Tech Fleece', 149.90, true, 140, 1, 2, 'https://picsum.photos/seed/bs037/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Moletom Adidas Entrada 22', 94.90, true, 200, 2, 2, 'https://picsum.photos/seed/bs038/400/300');

INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta Nike Dri-FIT Basketball', 79.90, true, 400, 1, 3, 'https://picsum.photos/seed/bs039/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta Adidas AEROREADY', 74.90, true, 350, 2, 3, 'https://picsum.photos/seed/bs040/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta Puma Active Small Logo', 69.90, true, 300, 3, 3, 'https://picsum.photos/seed/bs041/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta New Balance Athletics', 72.90, true, 280, 4, 3, 'https://picsum.photos/seed/bs042/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta Mizuno Team Performance', 69.90, true, 260, 5, 3, 'https://picsum.photos/seed/bs043/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Regata Nike Swingman', 89.90, true, 220, 1, 3, 'https://picsum.photos/seed/bs044/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Regata Adidas Performance', 84.90, false, 0, 2, 3, 'https://picsum.photos/seed/bs045/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta Puma Dribble', 74.90, true, 310, 3, 3, 'https://picsum.photos/seed/bs046/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta New Balance Court Tee', 69.90, true, 290, 4, 3, 'https://picsum.photos/seed/bs047/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta Nike Legend Tee', 79.90, true, 330, 1, 3, 'https://picsum.photos/seed/bs048/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta Adidas Squadra 21', 69.90, true, 300, 2, 3, 'https://picsum.photos/seed/bs049/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta Puma Liga Jersey', 74.90, true, 270, 3, 3, 'https://picsum.photos/seed/bs050/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Camiseta Mizuno Impulse', 69.90, true, 250, 5, 3, 'https://picsum.photos/seed/bs051/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Regata Nike Pro', 89.90, true, 200, 1, 3, 'https://picsum.photos/seed/bs052/400/300');

INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Calça de Treino Nike Basketball', 129.90, true, 250, 1, 4, 'https://picsum.photos/seed/bs053/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Calça Adidas Tiro 23', 119.90, true, 220, 2, 4, 'https://picsum.photos/seed/bs054/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bermuda Nike Dri-FIT DNA', 99.90, true, 300, 1, 4, 'https://picsum.photos/seed/bs055/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Calça Puma Training Knit', 109.90, true, 200, 3, 4, 'https://picsum.photos/seed/bs056/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bermuda New Balance Accelerate', 94.90, true, 280, 4, 4, 'https://picsum.photos/seed/bs057/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Calça Mizuno Knit Running', 119.90, false, 0, 5, 4, 'https://picsum.photos/seed/bs058/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Calça Nike Flex Woven', 129.90, true, 210, 1, 4, 'https://picsum.photos/seed/bs059/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bermuda Adidas 3-Stripes', 99.90, true, 290, 2, 4, 'https://picsum.photos/seed/bs060/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Calça Puma Basketball Warm Up', 114.90, true, 180, 3, 4, 'https://picsum.photos/seed/bs061/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bermuda Nike Court', 94.90, true, 260, 1, 4, 'https://picsum.photos/seed/bs062/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Calça New Balance Essentials Track', 104.90, true, 200, 4, 4, 'https://picsum.photos/seed/bs063/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Calça Adidas Condivo 22', 109.90, true, 190, 2, 4, 'https://picsum.photos/seed/bs064/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bermuda Mizuno Active', 89.90, true, 240, 5, 4, 'https://picsum.photos/seed/bs065/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bermuda Puma Active Woven', 94.90, true, 230, 3, 4, 'https://picsum.photos/seed/bs066/400/300');

INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Boné Nike Swoosh Legacy', 69.90, true, 350, 1, 5, 'https://picsum.photos/seed/bs067/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Boné Adidas 3-Stripes Aeroready', 64.90, true, 300, 2, 5, 'https://picsum.photos/seed/bs068/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Boné Puma Basketball', 59.90, true, 280, 3, 5, 'https://picsum.photos/seed/bs069/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Viseira New Balance Running', 54.90, true, 220, 4, 5, 'https://picsum.photos/seed/bs070/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Boné Mizuno Wave Cap', 59.90, false, 0, 5, 5, 'https://picsum.photos/seed/bs071/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Chapéu Nike Bucket Wash', 74.90, true, 200, 1, 5, 'https://picsum.photos/seed/bs072/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Boné Adidas Originals Trefoil', 69.90, true, 270, 2, 5, 'https://picsum.photos/seed/bs073/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Boné Puma Archive Logo', 64.90, true, 240, 3, 5, 'https://picsum.photos/seed/bs074/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Boné New Balance Athletics', 59.90, true, 260, 4, 5, 'https://picsum.photos/seed/bs075/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Chapéu Nike Heritage86', 74.90, true, 210, 1, 5, 'https://picsum.photos/seed/bs076/400/300');

INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Meias Nike Basketball Pack 3', 49.90, true, 500, 1, 6, 'https://picsum.photos/seed/bs077/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Munhequeira Adidas AEROREADY', 39.90, true, 400, 2, 6, 'https://picsum.photos/seed/bs078/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Joelheira Nike Pro', 59.90, true, 350, 1, 6, 'https://picsum.photos/seed/bs079/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Luva de Treino Puma', 54.90, true, 300, 3, 6, 'https://picsum.photos/seed/bs080/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Mochila Nike Hoops Elite', 199.90, true, 150, 1, 6, 'https://picsum.photos/seed/bs081/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Mochila Adidas Athletics 5-Star', 179.90, true, 130, 2, 6, 'https://picsum.photos/seed/bs082/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Toalha Puma Basketball', 44.90, true, 400, 3, 6, 'https://picsum.photos/seed/bs083/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Munhequeira Nike Dri-FIT', 34.90, true, 450, 1, 6, 'https://picsum.photos/seed/bs084/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Meia Mizuno Active Pack 3', 44.90, false, 0, 5, 6, 'https://picsum.photos/seed/bs085/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Mochila New Balance Sport', 149.90, true, 140, 4, 6, 'https://picsum.photos/seed/bs086/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Caneleira Nike Pro', 64.90, true, 320, 1, 6, 'https://picsum.photos/seed/bs087/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bolsa Nike Gym Club', 89.90, true, 200, 1, 6, 'https://picsum.photos/seed/bs088/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Faixas de Cabelo Adidas Pack 5', 29.90, true, 600, 2, 6, 'https://picsum.photos/seed/bs089/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Squeeze Nike Hyperfuel', 79.90, true, 250, 1, 6, 'https://picsum.photos/seed/bs090/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bolsa de Quadra Adidas Team', 129.90, true, 180, 2, 6, 'https://picsum.photos/seed/bs091/400/300');

INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Nike Official Game', 149.90, true, 300, 1, 7, 'https://picsum.photos/seed/bs092/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Treinamento Adidas Pro', 129.90, true, 280, 2, 7, 'https://picsum.photos/seed/bs093/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Puma Indoor', 119.90, true, 200, 3, 7, 'https://picsum.photos/seed/bs094/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete New Balance Street', 99.90, true, 220, 4, 7, 'https://picsum.photos/seed/bs095/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Mini Bola Adidas Kids Basketball', 45.90, true, 350, 2, 7, 'https://picsum.photos/seed/bs096/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Basquete Nike Outdoor', 89.90, false, 0, 1, 7, 'https://picsum.photos/seed/bs097/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola de Treino Puma Youth', 69.90, true, 260, 3, 7, 'https://picsum.photos/seed/bs098/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola Mizuno Competition', 109.90, true, 190, 5, 7, 'https://picsum.photos/seed/bs099/400/300');
INSERT OR IGNORE INTO products_table (name, price, availability, quantity, brand_id, category_id, image_url) VALUES ('Bola Nike All-Court', 95.90, true, 230, 1, 7, 'https://picsum.photos/seed/bs100/400/300');

INSERT OR IGNORE INTO payments_methods_table (title) VALUES ('Pix');
INSERT OR IGNORE INTO payments_methods_table (title) VALUES ('Cartão de Débito');
INSERT OR IGNORE INTO payments_methods_table (title) VALUES ('Cartão de Crédito');
